### ISSUE TITLE
Lab 2

### ISSUE THREAD

**Issue by duarteneves** [FilipeAfonso1710/FilipeAfonso1710.github.io#1]
A página index.html na raiz do teu projeto deve ser atualizada para conter links para todos os labs realizados.
Lab 2 muito incompleto.
A página loca.html não tem a estrutura da página bem definida, falta fechar a tag html. O objetivo n era ter uma imagem do google maps, mas sim, incorporar na página o mapa do google maps com recurso à tag iframe do html.

Resolver os issues até á próxima aula prática.

**Comment by FilipeAfonso22304588** [comment]
Olá professor. Já realizei algumas mudanças no Domingo mas o Commit & Push estava a dar algum erro por nunca terminar o processo. No entanto já so me falta o info.html e colocar os links dos Labs na página index
